name: Deploy Serverless

on:
  push:
    branches:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install dependencies
        run: npm ci

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: serverless deploy --verbose
# Step to Deploy API Gateway to a Stage
      - name: Deploy API Gateway to Stage
        env:
          DEPLOYMENT_STAGE: ${{ secrets.DEPLOYMENT_STAGE }}
          API_ID: ${{ secrets.API_ID }}
        run: |
          echo "Deploying API Gateway"
          aws apigateway create-deployment --rest-api-id ${{ secrets.API_ID }} --stage-name ${{ secrets.DEPLOYMENT_STAGE }}